# Generated by Django 5.2.8 on 2025-11-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('crmlite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='crmlite.company'),
        ),
    ]
