# Generated by Django 5.2.8 on 2025-11-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='company_id',
            new_name='company',
        ),
    ]
