# Generated by Django 5.2.8 on 2025-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0002_rename_company_id_storage_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
