# Generated by Django 5.2.8 on 2025-11-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0003_alter_company_options_alter_storage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='crmlite.company'),
        ),
    ]
