# Generated by Django 5.2.8 on 2025-11-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0005_supplier_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('purchase_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='crmlite.storage')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmlite.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmlite.supply')),
            ],
            options={
                'verbose_name': 'ПоставкаТовар',
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='products',
            field=models.ManyToManyField(related_name='supplies', through='crmlite.SupplyProduct', to='crmlite.product'),
        ),
    ]
