# Generated by Django 5.2.8 on 2025-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0006_product_supplyproduct_supply_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
