# Generated by Django 5.2.8 on 2025-11-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmlite', '0007_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplyproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplyproduct',
            name='supply',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='SupplyProduct',
        ),
    ]
